### ISSUE TITLE
Request to Revise Attribute on Profile and CVs

### ISSUE THREAD

**Issue by kulkasdingin** [kulkasdingin/laravel-resume#6]
- [x] Add description attribute to profile and CV -> Intention: having a field to describe about profile on the cv

- [x] Change gender data structure on CV to string

**Comment by kulkasdingin** [comment]
- [x] Add UUID to cv -> auto generated

**Comment by douglasraevan** [comment]
- [x] Change reference from CV to Profile ID instead of User ID

**Comment by douglasraevan** [comment]
- [x] Add name to CV

**Comment by ramawajdika** [comment]
Add endpoint for list of CVs for Profile
